[package]
name = "idf_env"
version = "1.1.6"
authors = ["Juraj Michalek <juraj.michalek@espressif.com>"]
edition = "2018"

[dependencies]
anyhow = "*"
clap = "*"
clap-nested = "*"
dirs = "*"
json = "*"
md5 = "*"
num_cpus = "*"
reqwest = "*"
# Fixed HJSON version, because of failed parsing of HJSON on latest version
# https://github.com/hjson/hjson-rust/issues/23#issuecomment-775520018
serde-hjson = { version = "0.9", default-features = false }
tokio = { version = "1", features = ["full"] }
walkdir = "*"
wmi = "*"
widestring = "*"
winapi = { version = "*", features = ["setupapi", "handleapi", "processthreadsapi", "winnt", "securitybaseapi", "impl-default", "shellapi"] }
zip = "*"

[[bin]]
name = "idf-env"
path = "src/idf_env.rs"
