[package]
name = "idf_env"
version = "1.1.2"
authors = ["Juraj Michalek <juraj.michalek@espressif.com>"]
edition = "2018"

[dependencies]
clap = "*"
clap-nested = "*"
json = "*"
md5 = "*"
reqwest = "*"
tokio = { version = "1", features = ["full"] }
wmi = "*"
widestring = "*"
winapi = { version = "*", features = ["setupapi", "handleapi", "processthreadsapi", "winnt", "securitybaseapi", "impl-default", "shellapi"] }
zip = "*"

[[bin]]
name = "idf-env"
path = "src/idf_env.rs"
