[package]
name = "idf-env"
version = "1.2.5"
authors = ["Juraj Michalek <juraj.michalek@espressif.com>"]
edition = "2018"

[dependencies]
anyhow = "*"
clap = "*"
clap-nested = "*"
dirs = "*"
flate2 = "1.0.22"
guess_host_triple = "0.1.3"
json = "*"
md5 = "*"
num_cpus = "*"
reqwest = "*"
tar = "0.4.37"
tokio = { version = "1", features = ["full"] }
walkdir = "*"
wmi = "*"
widestring = "*"
winapi = { version = "*", features = ["setupapi", "handleapi", "processthreadsapi", "winnt", "securitybaseapi", "impl-default", "shellapi"] }
zip = "*"
xz2 = "0.1.6"

[target.'cfg(windows)'.dependencies]
winreg = "0.7"

[[bin]]
name = "idf-env"
path = "src/idf_env.rs"
