[package]
name = "idf_env"
version = "1.2.1"
authors = ["Juraj Michalek <juraj.michalek@espressif.com>"]
edition = "2018"

[dependencies]
anyhow = "*"
clap = "*"
clap-nested = "*"
dirs = "*"
# Using Druid from source code, because of issue with 0.7 https://github.com/linebender/druid/issues/1739
druid = { git = "https://github.com/linebender/druid.git" }
json = "*"
md5 = "*"
num_cpus = "*"
reqwest = "*"
tokio = { version = "1", features = ["full"] }
walkdir = "*"
wmi = "*"
widestring = "*"
winapi = { version = "*", features = ["setupapi", "handleapi", "processthreadsapi", "winnt", "securitybaseapi", "impl-default", "shellapi"] }
zip = "*"

[[bin]]
name = "idf-env"
path = "src/idf_env.rs"
