[package]
name = "idf_env"
version = "1.2.4"
authors = ["Juraj Michalek <juraj.michalek@espressif.com>"]
edition = "2018"

[dependencies]
anyhow = "*"
clap = "*"
clap-nested = "*"
dirs = "*"
# guess_host_triple is missing aarch64-apple-darwin - open MR: https://gitlab.com/Screwtapello/guess_host_triple/-/merge_requests/3/diffs
guess_host_triple = { git = "https://gitlab.com/juraj.michalek/guess_host_triple.git", branch = "feature/aarch64-apple-darwin" }
json = "*"
md5 = "*"
num_cpus = "*"
reqwest = "*"
tokio = { version = "1", features = ["full"] }
walkdir = "*"
wmi = "*"
widestring = "*"
winapi = { version = "*", features = ["setupapi", "handleapi", "processthreadsapi", "winnt", "securitybaseapi", "impl-default", "shellapi"] }
zip = "*"

[target.'cfg(windows)'.dependencies]
winreg = "0.7"

[[bin]]
name = "idf-env"
path = "src/idf_env.rs"
