name: sign-espup

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: EspUp release version
        required: true
env:
  CARGO_TERM_COLOR: always

jobs:
  sign_release:
    name: Sign EspUp release
    runs-on: windows-latest
    steps:
      - name: Checkout idf-env repo
        uses: actions/checkout@v3
      - name: Checkout espup repository
        uses: actions/checkout@v2
        with:
          repository: esp-rs/espup
          ref: ${{ inputs.release-version }}
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          target: x86_64-pc-windows-msvc
          override: true
      - name: Cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Sign artifact
        env:
          CERTIFICATE: ${{ secrets.CERTIFICATE }}
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
        shell: pwsh
        run: ./Sign-File.ps1 -Path target/release/espup.exe
      - name: Archive artifact
        uses: actions/upload-artifact@v3
        with:
          name: espup-x86_64-pc-windows-msvc.exe
          path: target/release/espup.exe
